routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [
    'uses' => 'BlogController@index',
    'as' => 'blog'
]);

Route::get('/blog/{post}', [
    'uses' => 'BlogController@show',
    'as' => 'blog.show'
]);

Route::post('/blog/{post}', [
    'uses' => 'BlogController@comment',
    'as' => 'blog.comment'
]);

Route::get('/category/{category}', [
    'uses' => 'BlogController@category',
    'as' => 'category'
]);

Route::get('/author/{author}', [
    'uses' => 'BlogController@author',
    'as' => 'author'
]);

Route::get('/tag/{tag}', [
    'uses' => 'BlogController@tag',
    'as' => 'tag'
]);

Auth::routes(['register' => false]);

Route::get('/backend/home', 'Backend\HomeController@index')->name('home');

Route::name('backend.')->group(function(){
    Route::resource('/backend/blog', 'Backend\BlogController');
    Route::put('/backend/blog/restore/{blog}', [
        'uses' => 'Backend\BlogController@restore',
        'as' => 'blog.restore'
    ]);
    Route::delete('/backend/blog/force-destroy/{blog}', [
        'uses' => 'Backend\BlogController@forceDestroy',
        'as' => 'blog.force-destroy'
    ]);
    Route::resource('/backend/category', 'Backend\CategoryController');
    Route::resource('/backend/user', 'Backend\UserController');
    Route::get('/backend/user/confirm/{user}', [
        'uses' => 'Backend\UserController@confirm',
        'as' => 'user.confirm'
    ]);
    Route::get('backend/account/edit', [
        'uses' => 'Backend\HomeController@edit',
        'as' => 'account.edit'
    ]);
    Route::put('backend/account/edit', [
        'uses' => 'Backend\HomeController@update',
        'as' => 'account.update'
    ]);
    Route::resource('/backend/tag', 'Backend\TagController');
});

app/Post.php
<?php

namespace App;

use Carbon\Carbon;
use GrahamCampbell\Markdown\Facades\Markdown;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Str;
use Intervention\Image\Facades\Image;

class Post extends Model
{
    use SoftDeletes;

    protected $fillable = [
        'title', 'slug', 'excerpt', 'body', 'image', 'published_at', 'category_id'
    ];

    protected $dates = ['published_at'];

    public function __construct(array $attributes = [])
    {
        parent::__construct($attributes);
    }

    public function author()
    {
        return $this->belongsTo(User::class);
    }

    public function category(){
        return $this->belongsTo(Category::class);
    }

    public function tags()
    {
        return $this->belongsToMany(Tag::class);
    }

    public function comments()
    {
        return $this->hasMany(Comment::class);
    }

    public function setPublishedAtAttribute($value){
        $this->attributes['published_at'] = $value ?: null;
    }

    public function setImageAttribute($value){
        if(!app()->runningInConsole())
        {
            if($value instanceof UploadedFile){
                $this->deleteImage();
                $success = $value->move(config('cms.image.directory'), $value->getClientOriginalName());
                if($success){
                    Image::make(config('cms.image.directory').'/'.$value->getClientOriginalName())
                        ->resize(config('cms.image.thumbnail.width'), config('cms.image.thumbnail.height'))
                        ->save(config('cms.image.directory') . '/' .str_replace(".{$value->getClientOriginalExtension()}", "_thumb.{$value->getClientOriginalExtension()}", $value->getClientOriginalName()));
                }
                $this->attributes['image'] = $value->getClientOriginalName();
            }
        }
        else
        {
            $this->attributes['image'] = $value;
        }
    }

    protected function deleteImage()
    {
        if(File::exists(config('cms.image.directory') . '/' . $this->image)){
            File::delete(config('cms.image.directory') . '/' . $this->image);
            $ext = substr(strrchr($this->image, '.'), 1);
            $thumbnail = str_replace(".{$ext}", "_thumb.{$ext}", $this->image);
            File::delete(config('cms.image.directory') . '/' . $thumbnail);
        }
    }

    public function forceDelete()
    {
        $this->deleteImage();
        return parent::forceDelete(); // TODO: Change the autogenerated stub
    }

    public function getImageUrlAttribute(){

        $imageUrl = '';

        if(!is_null($this->image))
        {
            if(file_exists(public_path() . '/' .config('cms.image.directory') . '/' . $this->image)){
                $imageUrl = asset(config('cms.image.directory') . '/' . $this->image);
            }
        }

        return $imageUrl;
    }

    public function getImageThumbUrlAttribute(){

        $imageUrl = '';

        if(!is_null($this->image))
        {
            $ext = substr(strrchr($this->image, '.'), 1);
            $thumbnail = str_replace(".{$ext}", "_thumb.{$ext}", $this->image);
            if(file_exists(public_path() . '/' .config('cms.image.directory'). '/' . $thumbnail)){
                $imageUrl = asset(config('cms.image.directory') . '/' . $thumbnail);
            }
        }

        return $imageUrl;
    }

    public function getDateAttribute(){
        return is_null($this->published_at) ? '' : $this->published_at->diffForHumans();
    }

    public function getBodyHtmlAttribute(){
        return $this->body ? Markdown::convertToHtml(e($this->body)) : null;
    }

    public function getExcerptHtmlAttribute(){
        return $this->excerpt ? Markdown::convertToHtml(e($this->excerpt)) : null;
    }

    public function getTagsHtmlAttribute()
    {
        $tags = [];
        foreach($this->tags as $tag)
        {
            $route = route('tag', $tag->slug);
            $tags[] = "<a href=\"{$route}\">{$tag->name}</a>";
        }
        return implode(', ', $tags);
    }

    public function getCommentCountAttribute()
    {
        $commentsCount = $this->comments->count();
        return $commentsCount . ' ' . Str::plural('Comment', $commentsCount);
    }

    public function getAuthorPostCountAttribute()
    {
        $authorPostCount = $this->author->posts()->published()->count();
        return $authorPostCount . ' ' . Str::plural('post', $authorPostCount);
    }

    public function postTags($implode = true)
    {
        $tags = $this->tags->pluck('name')->toArray();
        if($implode) return implode(', ', $tags);
        return $tags;
    }

    public function dateFormatted($showTimes = false){
        $format = 'd/m/Y';
        if($showTimes) $format .= ' H:i:s';
        return $this->created_at->format($format);
    }

    public function deletionDateFormatted(){
        return $this->deleted_at->format('d/m/Y');
    }

    public function publicationLabel()
    {
        if(!$this->published_at) return '<span class="label label-warning">Draft</span>';
        elseif($this->published_at && $this->published_at->isFuture()) return '<span class="label label-info">Scheduled</span>';
        else return '<span class="label label-success">Published</span>';
    }

    public function scopeLatestFirst($query){
        //can be used latest() built-in function
        return $query->orderBy('published_at', 'desc');
    }

    public function scopePopular($query)
    {
        return $query->orderBy('view_count', 'desc');
    }

    public function scopePublished($query)
    {
        return $query->where('published_at', '<=', Carbon::now());
    }

    public function scopeScheduled($query)
    {
        return $query->where('published_at', '>', Carbon::now());
    }

    public function scopeDraft($query)
    {
        return $query->whereNull('published_at');
    }

    public function scopeArchives($query)
    {
        return $query->selectRaw('COUNT(id) AS post_count, YEAR(published_at) as year, MONTHNAME(published_at) as month')->published()->groupBy('year','month')->orderByRaw('min(published_at) desc');
    }

    public function scopeFilter($query, $filter)
    {
        if(isset($filter['month']) && $month = $filter['month'])
        {
            $query->whereMonth('published_at', Carbon::parse($month)->month);
        }
        if(isset($filter['year']) && $year = $filter['year'])
        {
            $query->whereYear('published_at', $year);
        }
        if(isset($filter['term']) &&  $term = $filter['term'])
        {
            $query->where(function($q) use ($term){
                $q->orWhere('title', 'LIKE', "%{$term}%");
                $q->orWhere('excerpt', 'LIKE', "%{$term}%");
                $q->orWhere('body', 'LIKE', "%{$term}%");
                $q->orWhereHas('author', function($subQuery) use ($term){
                    $subQuery->where('name', 'LIKE', "%{$term}%");
                });
                $q->orWhereHas('category', function($subQuery) use ($term){
                    $subQuery->where('title', 'LIKE', "%{$term}%");
                });
            });
        }
        return $query;
    }

    public function attachTags($tags)
    {
        $tags = explode(",", $tags);
        $tagIds = [];

        foreach ($tags as $tag)
        {
            $newTag = Tag::firstOrCreate([
                'name' => ucwords(trim($tag)),
                'slug' => Str::slug($tag)
            ]);

            $tagIds[] = $newTag->id;
        }

        $this->tags()->sync($tagIds);
    }
}

app/User.php
<?php

namespace App;

use GrahamCampbell\Markdown\Facades\Markdown;
use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Support\Facades\Hash;
use Laratrust\Traits\LaratrustUserTrait;

class User extends Authenticatable
{
    use Notifiable;
    use LaratrustUserTrait;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'slug', 'bio',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function posts(){
        return $this->hasMany(Post::class, 'author_id');
    }

    public function gravatar(){
        $email = $this->email;
        $default = asset('img/author.jpg');
        $size = 100;

        return "https://www.gravatar.com/avatar/" . md5( strtolower( trim( $email ) ) ) . "?d=" . urlencode( $default ) . "&s=" . $size;

    }

    public function getBioHtmlAttribute(){
        return $this->bio ? Markdown::convertToHtml(e($this->bio)) : null;
    }

    public function getRegisteredDateAttribute(){
        if($this->email_verified_at) return $this->email_verified_at->toDayDateTimeString();
        return $this->created_at->toDayDateTimeString();
    }

    public function getRouteKeyName()
    {
        return 'slug';
    }

    public function setPasswordAttribute($value)
    {
        if(!empty($value)) $this->attributes['password'] = Hash::make($value);
    }
}

app/Http/Controllers/Backend/BlogController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Forms\PostForm;
use App\Post;
use Illuminate\Http\Request;
use Kris\LaravelFormBuilder\FormBuilder;
use Kris\LaravelFormBuilder\FormBuilderTrait;

class BlogController extends BackendController
{
    use FormBuilderTrait;

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $onlyTrashed = false;
        if(($status = $request->get('status')) && $status == 'trash')
        {
            $posts = Post::onlyTrashed()->with('category', 'author')->latest()->paginate($this->limit);
            $onlyTrashed = true;
        }
        elseif($status == 'published')
        {
            $posts = Post::published()->with('category', 'author')->latest()->paginate($this->limit);
        }
        elseif($status == 'scheduled')
        {
            $posts = Post::scheduled()->with('category', 'author')->latest()->paginate($this->limit);
        }
        elseif($status == 'draft')
        {
            $posts = Post::draft()->with('category', 'author')->latest()->paginate($this->limit);
        }
        elseif($status == 'own')
        {
            $posts = $request->user()->posts()->with('category', 'author')->latest()->paginate($this->limit);
        }
        else
        {
            $posts = Post::withTrashed()->with('category', 'author')->latest()->paginate($this->limit);
        }
        return view('backend.blog.index', compact('posts', 'onlyTrashed'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(FormBuilder $formBuilder)
    {
        $form = $formBuilder->create(PostForm::class, [
            'method' => 'POST',
            'url' => route('backend.blog.store')
        ]);
        return view('backend.blog.edit', compact('form'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $form = $this->form(PostForm::class);

        // It will automatically use current request, get the rules, and do the validation
        if (!$form->isValid()) {
            return redirect()->back()->withErrors($form->getErrors())->withInput();
        }

        // Or automatically redirect on error. This will throw an HttpResponseException with redirect
        $form->redirectIfNotValid();

        $data = $form->getFieldValues();

        $post = $request->user()->posts()->create($data);
        $post->attachTags($data['post_tags']);

        return redirect()->route('backend.blog.index')->with('success', 'Your post was created successfully!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     *
     * @todo the controller does not receive Post object
     */
    public function edit($id, FormBuilder $formBuilder)
    {
        $post = Post::findOrFail($id);

        $form = $formBuilder->create(PostForm::class, [
            'method' => 'PUT',
            'url' => route('backend.blog.update', ['id' => $id]),
            'model' => $post
        ]);
        return view('backend.blog.edit', compact('form'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $form = $this->form(PostForm::class);

        // It will automatically use current request, get the rules, and do the validation
        if (!$form->isValid()) {
            return redirect()->back()->withErrors($form->getErrors())->withInput();
        }

        // Or automatically redirect on error. This will throw an HttpResponseException with redirect
        $form->redirectIfNotValid();

        $data = $form->getFieldValues();

        $post = Post::findOrFail($id);
        $post->update($data);
        $post->attachTags($data['post_tags']);

        return redirect()->route('backend.blog.index')->with('success', 'Your post was updated successfully!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Post::destroy($id);
        return redirect()->back()->with('trash-message', ['Your post was moved to trash!', $id]);
    }

    /**
     * @param $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function forceDestroy($id)
    {
        Post::onlyTrashed()->findOrFail($id)->forceDelete();
        return redirect()->back()->with('message', 'Your post was deleted permanently!');
    }

    /**
     * @param $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function restore($id)
    {
        Post::onlyTrashed()->findOrFail($id)->restore();
        return redirect()->back()->with('message', 'Your post was restored!');
    }
}

resources/views/blog/alert.blade.php
@if(isset($categoryName))
    <div class="alert alert-info">
        <p>Category: <strong>{{ $categoryName }}</strong></p>
    </div>
@endif

@if(isset($authorName))
    <div class="alert alert-info">
        <p>Author: <strong>{{ $authorName }}</strong></p>
    </div>
@endif

@if(isset($tagName))
    <div class="alert alert-info">
        <p>Tagged: <strong>{{ $tagName }}</strong></p>
    </div>
@endif

@if(request('term'))
    <div class="alert alert-info">
        <p>Search Results for: <strong>{{ request('term') }}</strong></p>
    </div>
@endif

resources/views/blog/comments.blade.php
<a name="comments"></a>
<article class="post-comments">
    <h3><i class="fa fa-comments"></i>{{ $post->comment_count }}</h3>

    <div class="comment-body padding-10">
        <ul class="comments-list">
            @forelse($postComments as $comment)
            <li class="comment-item">
                <div class="comment-heading clearfix">
                    <div class="comment-author-meta">
                        <h4>{{ $comment->author_name }} <small>{{ $comment->date }}</small></h4>
                    </div>
                </div>
                <div class="comment-content">
                    {!! $comment->body_html !!}
                </div>
            </li>
            @empty
            <li class="comment-item">
                <div class="comment-content">
                    <p>There are no comments yet.</p>
                </div>
            </li>
            @endforelse
        </ul>
        <nav>
            {!! $postComments->links() !!}
        </nav>
    </div>

    <div class="comment-footer padding-10">
        <h3>Leave a comment</h3>
        {!! form($form) !!}
    </div>

</article>

resources/views/blog/index.blade.php
@extends('layouts.main')

@section('content')

<div class="container">
    <div class="row">
        <div class="col-md-8">

            @include('blog.alert')

            @forelse($posts as $post)
            <article class="post-item panel-tranparent">
                @if($post->image_url)
                <div class="post-item-image">
                    <a href="{{ route('blog.show', $post->slug) }}">
                        <img src="{{ $post->image_url }}" alt="">
                    </a>
                </div>
                @endif
                <div class="post-item-body">
                    <div class="padding-10">
                        <h2><a href="{{ route('blog.show', $post->slug) }}">{{ $post->title }}</a></h2>
                        {!! $post->excerpt_html !!}
                    </div>

                    <div class="post-meta padding-10 clearfix">
                        <div class="pull-left">
                            <ul class="post-meta-group">
                                <li><i class="fa fa-user"></i><a href="{{ route('author', $post->author->slug) }}"> {{ $post->author->name }}</a></li>
                                <li><i class="fa fa-clock-o"></i><time> {{ $post->date }}</time></li>
                                <li><i class="fa fa-folder"></i><a href="{{ route('category', $post->category->slug) }}"> {{ $post->category->title }}</a></li>
                                <li><i class="fa fa-tag"></i>{!! $post->tags_html !!}</li>
                                <li><i class="fa fa-comments"></i>
                                    <a href="{{ route('blog.show', $post->slug) }}#comments">{{ $post->comment_count }}</a>
                                </li>
                            </ul>
                        </div>
                        <div class="pull-right">
                            <a href="{{ route('blog.show', $post->slug) }}" class="main-theme-arsyfa-button">Continue Reading &raquo;</a>
                        </div>
                    </div>
                </div>
            </article>
            @empty
            <div class="alert alert-warning">
                <p>Nothing Found</p>
            </div>
            @endforelse

            <nav>
                {{ $posts->appends(request()->only(['term', 'year', 'month']))->links() }}
            </nav>
        </div>
        @include('layouts.sidebar')
    </div>
</div>
@endsection

resources/views/blog/show.blade.php
@extends('layouts.main')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <article class="post-item post-detail">

                    @if($post->image_url)
                    <div class="post-item-image">
                        <img src="{{ $post->image_url }}" alt="{{ $post->title }}">
                    </div>
                    @endif

                    <div class="post-item-body">
                        <div class="padding-10">
                            <h1>{{ $post->title }}</h1>

                            <div class="post-meta no-border">
                                <ul class="post-meta-group">
                                    <li><i class="fa fa-user"></i><a href="{{ route('author', $post->author->slug) }}"> {{ $post->author->name }}</a></li>
                                    <li><i class="fa fa-clock-o"></i><time> {{ $post->date }}</time></li>
                                    <li><i class="fa fa-folder"></i><a href="{{ route('category', $post->category->slug) }}"> {{ $post->category->title }}</a></li>
                                    <li><i class="fa fa-tag"></i>{!! $post->tags_html !!}</li>
                                    <li><i class="fa fa-comments"></i>
                                        <a href="#comments">{{ $post->comment_count }}</a>
                                    </li>
                                </ul>
                            </div>

                            {!!  $post->body_html !!}

                        </div>
                    </div>
                </article>

                <article class="post-author padding-10">
                    <div class="media">
                        <div class="media-left">
                            <a href="{{ route('author', $post->author->slug) }}">
                                <img alt="{{ $post->author->name }}" src="{{ $post->author->gravatar() }}" class="media-object">
                            </a>
                        </div>
                        <div class="media-body">
                            <h4 class="media-heading"><a href="{{ route('author', $post->author->slug) }}">{{ $post->author->name }}</a></h4>
                            <div class="post-author-count">
                                <a href="{{ route('author', $post->author->slug) }}">
                                    <i class="fa fa-clone"></i> {{ $post->author_post_count }}
                                </a>
                            </div>
                            {!! $post->author->bio_html !!}
                        </div>
                    </div>
                </article>

                @if(session('success'))
                    <div class="alert alert-success">
                        {{ session('success') }}
                    </div>
                @endif

                @include('blog.comments')

            </div>
            @include('layouts.sidebar')
        </div>
    </div>
@endsection