routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [
    'uses' => 'BlogController@index',
    'as' => 'blog'
]);

Route::get('/blog/{post}', [
    'uses' => 'BlogController@show',
    'as' => 'blog.show'
]);

Route::post('/blog/{post}', [
    'uses' => 'BlogController@comment',
    'as' => 'blog.comment'
]);

Route::get('/category/{category}', [
    'uses' => 'BlogController@category',
    'as' => 'category'
]);

Route::get('/author/{author}', [
    'uses' => 'BlogController@author',
    'as' => 'author'
]);

Route::get('/tag/{tag}', [
    'uses' => 'BlogController@tag',
    'as' => 'tag'
]);

Auth::routes(['register' => false]);

Route::get('/backend/home', 'Backend\HomeController@index')->name('home');

Route::name('backend.')->group(function(){
    Route::resource('/backend/blog', 'Backend\BlogController');
    Route::put('/backend/blog/restore/{blog}', [
        'uses' => 'Backend\BlogController@restore',
        'as' => 'blog.restore'
    ]);
    Route::delete('/backend/blog/force-destroy/{blog}', [
        'uses' => 'Backend\BlogController@forceDestroy',
        'as' => 'blog.force-destroy'
    ]);
    Route::resource('/backend/category', 'Backend\CategoryController');
    Route::resource('/backend/user', 'Backend\UserController');
    Route::get('/backend/user/confirm/{user}', [
        'uses' => 'Backend\UserController@confirm',
        'as' => 'user.confirm'
    ]);
    Route::get('backend/account/edit', [
        'uses' => 'Backend\HomeController@edit',
        'as' => 'account.edit'
    ]);
    Route::put('backend/account/edit', [
        'uses' => 'Backend\HomeController@update',
        'as' => 'account.update'
    ]);
    Route::resource('/backend/tag', 'Backend\TagController');
});

app/Post.php
<?php

namespace App;

use Carbon\Carbon;
use GrahamCampbell\Markdown\Facades\Markdown;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Str;
use Intervention\Image\Facades\Image;

class Post extends Model
{
    use SoftDeletes;

    protected $fillable = [
        'title', 'slug', 'excerpt', 'body', 'image', 'published_at', 'category_id'
    ];

    protected $dates = ['published_at'];

    public function __construct(array $attributes = [])
    {
        parent::__construct($attributes);
    }

    public function author()
    {
        return $this->belongsTo(User::class);
    }

    public function category(){
        return $this->belongsTo(Category::class);
    }

    public function tags()
    {
        return $this->belongsToMany(Tag::class);
    }

    public function comments()
    {
        return $this->hasMany(Comment::class);
    }

    public function setPublishedAtAttribute($value){
        $this->attributes['published_at'] = $value ?: null;
    }

    public function setImageAttribute($value){
        if(!app()->runningInConsole())
        {
            if($value instanceof UploadedFile){
                $this->deleteImage();
                $success = $value->move(config('cms.image.directory'), $value->getClientOriginalName());
                if($success){
                    Image::make(config('cms.image.directory').'/'.$value->getClientOriginalName())
                        ->resize(config('cms.image.thumbnail.width'), config('cms.image.thumbnail.height'))
                        ->save(config('cms.image.directory') . '/' .str_replace(".{$value->getClientOriginalExtension()}", "_thumb.{$value->getClientOriginalExtension()}", $value->getClientOriginalName()));
                }
                $this->attributes['image'] = $value->getClientOriginalName();
            }
        }
        else
        {
            $this->attributes['image'] = $value;
        }
    }

    protected function deleteImage()
    {
        if(File::exists(config('cms.image.directory') . '/' . $this->image)){
            File::delete(config('cms.image.directory') . '/' . $this->image);
            $ext = substr(strrchr($this->image, '.'), 1);
            $thumbnail = str_replace(".{$ext}", "_thumb.{$ext}", $this->image);
            File::delete(config('cms.image.directory') . '/' . $thumbnail);
        }
    }

    public function forceDelete()
    {
        $this->deleteImage();
        return parent::forceDelete(); // TODO: Change the autogenerated stub
    }

    public function getImageUrlAttribute(){

        $imageUrl = '';

        if(!is_null($this->image))
        {
            if(file_exists(public_path() . '/' .config('cms.image.directory') . '/' . $this->image)){
                $imageUrl = asset(config('cms.image.directory') . '/' . $this->image);
            }
        }

        return $imageUrl;
    }

    public function getImageThumbUrlAttribute(){

        $imageUrl = '';

        if(!is_null($this->image))
        {
            $ext = substr(strrchr($this->image, '.'), 1);
            $thumbnail = str_replace(".{$ext}", "_thumb.{$ext}", $this->image);
            if(file_exists(public_path() . '/' .config('cms.image.directory'). '/' . $thumbnail)){
                $imageUrl = asset(config('cms.image.directory') . '/' . $thumbnail);
            }
        }

        return $imageUrl;
    }

    public function getDateAttribute(){
        return is_null($this->published_at) ? '' : $this->published_at->diffForHumans();
    }

    public function getBodyHtmlAttribute(){
        return $this->body ? Markdown::convertToHtml(e($this->body)) : null;
    }

    public function getExcerptHtmlAttribute(){
        return $this->excerpt ? Markdown::convertToHtml(e($this->excerpt)) : null;
    }

    public function getTagsHtmlAttribute()
    {
        $tags = [];
        foreach($this->tags as $tag)
        {
            $route = route('tag', $tag->slug);
            $tags[] = "<a href=\"{$route}\">{$tag->name}</a>";
        }
        return implode(', ', $tags);
    }

    public function getCommentCountAttribute()
    {
        $commentsCount = $this->comments->count();
        return $commentsCount . ' ' . Str::plural('Comment', $commentsCount);
    }

    public function getAuthorPostCountAttribute()
    {
        $authorPostCount = $this->author->posts()->published()->count();
        return $authorPostCount . ' ' . Str::plural('post', $authorPostCount);
    }

    public function postTags($implode = true)
    {
        $tags = $this->tags->pluck('name')->toArray();
        if($implode) return implode(', ', $tags);
        return $tags;
    }

    public function dateFormatted($showTimes = false){
        $format = 'd/m/Y';
        if($showTimes) $format .= ' H:i:s';
        return $this->created_at->format($format);
    }

    public function deletionDateFormatted(){
        return $this->deleted_at->format('d/m/Y');
    }

    public function publicationLabel()
    {
        if(!$this->published_at) return '<span class="label label-warning">Draft</span>';
        elseif($this->published_at && $this->published_at->isFuture()) return '<span class="label label-info">Scheduled</span>';
        else return '<span class="label label-success">Published</span>';
    }

    public function scopeLatestFirst($query){
        //can be used latest() built-in function
        return $query->orderBy('published_at', 'desc');
    }

    public function scopePopular($query)
    {
        return $query->orderBy('view_count', 'desc');
    }

    public function scopePublished($query)
    {
        return $query->where('published_at', '<=', Carbon::now());
    }

    public function scopeScheduled($query)
    {
        return $query->where('published_at', '>', Carbon::now());
    }

    public function scopeDraft($query)
    {
        return $query->whereNull('published_at');
    }

    public function scopeArchives($query)
    {
        return $query->selectRaw('COUNT(id) AS post_count, YEAR(published_at) as year, MONTHNAME(published_at) as month')->published()->groupBy('year','month')->orderByRaw('min(published_at) desc');
    }

    public function scopeFilter($query, $filter)
    {
        if(isset($filter['month']) && $month = $filter['month'])
        {
            $query->whereMonth('published_at', Carbon::parse($month)->month);
        }
        if(isset($filter['year']) && $year = $filter['year'])
        {
            $query->whereYear('published_at', $year);
        }
        if(isset($filter['term']) &&  $term = $filter['term'])
        {
            $query->where(function($q) use ($term){
                $q->orWhere('title', 'LIKE', "%{$term}%");
                $q->orWhere('excerpt', 'LIKE', "%{$term}%");
                $q->orWhere('body', 'LIKE', "%{$term}%");
                $q->orWhereHas('author', function($subQuery) use ($term){
                    $subQuery->where('name', 'LIKE', "%{$term}%");
                });
                $q->orWhereHas('category', function($subQuery) use ($term){
                    $subQuery->where('title', 'LIKE', "%{$term}%");
                });
            });
        }
        return $query;
    }

    public function attachTags($tags)
    {
        $tags = explode(",", $tags);
        $tagIds = [];

        foreach ($tags as $tag)
        {
            $newTag = Tag::firstOrCreate([
                'name' => ucwords(trim($tag)),
                'slug' => Str::slug($tag)
            ]);

            $tagIds[] = $newTag->id;
        }

        $this->tags()->sync($tagIds);
    }
}

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>AdminLTE 2 | Log in</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.6 -->
    <link rel="stylesheet" href="/backend/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="/backend/css/AdminLTE.min.css">
    <!-- iCheck -->
    <link rel="stylesheet" href="/backend/plugins/iCheck/square/blue.css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body class="hold-transition login-page">
    @yield('content')
    <!-- jQuery 2.2.3 -->
    <script src="/backend/js/jquery-2.2.3.min.js"></script>
    <!-- Bootstrap 3.3.6 -->
    <script src="/backend/js/bootstrap.min.js"></script>
    <!-- iCheck -->
    <script src="/backend/plugins/iCheck/icheck.min.js"></script>
    <script>
        $(function () {
            $('input').iCheck({
                checkboxClass: 'icheckbox_square-blue',
                radioClass: 'iradio_square-blue',
                increaseArea: '20%' // optional
            });
        });
    </script>
</body>
</html>

resources/views/layouts/main.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Arsyfa Queen</title>    

    {!! SEOMeta::generate() !!}
    {!! OpenGraph::generate() !!}
    {!! Twitter::generate() !!}
    {!! JsonLd::generate() !!}
    {!! JsonLdMulti::generate() !!}

    <!-- OR -->
    {!! SEO::generate() !!}

    <!-- MINIFIED -->
    {!! SEO::generate(true) !!}

    <link href='https://fonts.googleapis.com/css?family=Raleway:400,700' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.css">
    <link rel="stylesheet" href="{{ asset('css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ asset('css/custom.css') }}">
    <script data-ad-client="ca-pub-9876588976105787" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-177833065-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'UA-177833065-1');
    </script>

    <!-- <meta name="google-site-verification" content="" /> -->

    <!-- Favicon -->
    <!-- <link rel="icon" type="image/png" href=""> -->
</head>
<body>
    <style type="text/css">
        .text-white {
            color: white !important;
        }
        .main-theme-arsyfa {
            background-color: black !important;
            color: white;
        }
        .panel-tranparent {
            opacity: 0.9 !important;
            border-radius: 5px;
        }    
        .main-theme-arsyfa-button {
            border: solid 1px gray;
            padding: 5px;
            border-radius: 15px;
            background: black !important;
            color: white !important;
        }
    </style>
<header>
    <nav class="navbar navbar-default navbar-fixed-top main-theme-arsyfa">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#the-navbar-collapse" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand text-white" href="{{ route('blog') }}">Beranda</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="the-navbar-collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li class="active"><a href="{{ route('blog') }}">Post</a></li>
                    <!-- <li><a href="#">About</a></li>
                    <li><a href="#">Contact</a></li> -->
                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container -->
    </nav>
</header>

@yield('content')

<footer class="main-theme-arsyfa">
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <p class="copyright text-white">&copy; 2021 ArsyfaITSolution</p>
            </div>
            <div class="col-md-4">
                <nav>
                    <ul class="social-icons">
                        <li><a href="#" class="i fa fa-facebook text-white"></a></li>
                        <li><a href="#" class="i fa fa-twitter text-white"></a></li>
                        <li><a href="#" class="i fa fa-google-plus text-white"></a></li>
                        <li><a href="#" class="i fa fa-instagram text-white"></a></li>
                    </ul>
                </nav>
            </div>
        </div>
    </div>
</footer>

<script src="{{ asset('js/bootstrap.min.js') }}"></script>
</body>
</html>

resources/views/layouts/sidebar.blade.php
<div class="col-md-4">
    <aside class="right-sidebar">

        <div class="search-widget panel-tranparent">
            <form action="{{ route('blog') }}">
                <div class="input-group">
                <input name="term" value="{{ request('term') }}" type="text" class="form-control input-lg" placeholder="Search for...">
                <span class="input-group-btn">
                    <button class="btn btn-lg btn-default" type="submit">
                        <i class="fa fa-search"></i>
                    </button>
                </span>
                </div>
            </form>
        </div>

        <div class="widget panel-tranparent">
            <div class="widget-heading">
                <h4>Categories</h4>
            </div>
            <div class="widget-body">
                <ul class="categories">
                    @foreach($categories as $category)
                    <li>
                        <a href="{{ route('category', $category->slug) }}"><i class="fa fa-angle-right"></i> {{ $category->title }}</a>
                        <span class="badge pull-right">{{ $category->posts->count() }}</span>
                    </li>
                    @endforeach
                </ul>
            </div>
        </div>

        <div class="widget panel-tranparent">
            <div class="widget-heading">
                <h4>Popular Posts</h4>
            </div>
            <div class="widget-body">
                <ul class="popular-posts">
                    @foreach($popularPosts as $post)
                    <li>
                        @if($post->image_thumb_url)
                        <div class="post-image">
                            <a href="{{ route('blog.show', $post->slug) }}">
                                <img src="{{ $post->image_thumb_url }}" />
                            </a>
                        </div>
                        @endif
                        <div class="post-body">
                            <h6><a href="{{ route('blog.show', $post->slug) }}">{{ $post->title }}</a></h6>
                            <div class="post-meta">
                                <span>{{ $post->date }}</span>
                            </div>
                        </div>
                    </li>
                    @endforeach
                </ul>
            </div>
        </div>

        <div class="widget panel-tranparent">
            <div class="widget-heading">
                <h4>Tags</h4>
            </div>
            <div class="widget-body">
                <ul class="tags">
                    @foreach($tags as $tag)
                        <li><a href="{{ route('tag', $tag->slug) }}">{{ $tag->name }}</a></li>
                    @endforeach
                </ul>
            </div>
        </div>

        <div class="widget panel-tranparent">
            <div class="widget-heading">
                <h4>Archives</h4>
            </div>
            <div class="widget-body">
                <ul class="categories">
                    @foreach($archives as $archive)
                        <li>
                            <a href="{{ route('blog', ['month' => $archive->month, 'year' => $archive->year]) }}">{{ $archive->month }} {{ $archive->year }}</a>
                            <span class="badge pull-right">{{ $archive->post_count }}</span>
                        </li>
                    @endforeach
                </ul>
            </div>
        </div>

    </aside>
</div>