routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [
    'uses' => 'BlogController@index',
    'as' => 'blog'
]);

Route::get('/blog/{post}', [
    'uses' => 'BlogController@show',
    'as' => 'blog.show'
]);

Route::post('/blog/{post}', [
    'uses' => 'BlogController@comment',
    'as' => 'blog.comment'
]);

Route::get('/category/{category}', [
    'uses' => 'BlogController@category',
    'as' => 'category'
]);

Route::get('/author/{author}', [
    'uses' => 'BlogController@author',
    'as' => 'author'
]);

Route::get('/tag/{tag}', [
    'uses' => 'BlogController@tag',
    'as' => 'tag'
]);

Auth::routes(['register' => false]);

Route::get('/backend/home', 'Backend\HomeController@index')->name('home');

Route::name('backend.')->group(function(){
    Route::resource('/backend/blog', 'Backend\BlogController');
    Route::put('/backend/blog/restore/{blog}', [
        'uses' => 'Backend\BlogController@restore',
        'as' => 'blog.restore'
    ]);
    Route::delete('/backend/blog/force-destroy/{blog}', [
        'uses' => 'Backend\BlogController@forceDestroy',
        'as' => 'blog.force-destroy'
    ]);
    Route::resource('/backend/category', 'Backend\CategoryController');
    Route::resource('/backend/user', 'Backend\UserController');
    Route::get('/backend/user/confirm/{user}', [
        'uses' => 'Backend\UserController@confirm',
        'as' => 'user.confirm'
    ]);
    Route::get('backend/account/edit', [
        'uses' => 'Backend\HomeController@edit',
        'as' => 'account.edit'
    ]);
    Route::put('backend/account/edit', [
        'uses' => 'Backend\HomeController@update',
        'as' => 'account.update'
    ]);
    Route::resource('/backend/tag', 'Backend\TagController');
});

app/Http/Controllers/Backend/BackendController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class BackendController extends Controller
{
    protected $limit = 10;

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('check-permissions');
    }
}

app/Http/Controllers/Backend/BlogController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Forms\PostForm;
use App\Post;
use Illuminate\Http\Request;
use Kris\LaravelFormBuilder\FormBuilder;
use Kris\LaravelFormBuilder\FormBuilderTrait;

class BlogController extends BackendController
{
    use FormBuilderTrait;

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $onlyTrashed = false;
        if(($status = $request->get('status')) && $status == 'trash')
        {
            $posts = Post::onlyTrashed()->with('category', 'author')->latest()->paginate($this->limit);
            $onlyTrashed = true;
        }
        elseif($status == 'published')
        {
            $posts = Post::published()->with('category', 'author')->latest()->paginate($this->limit);
        }
        elseif($status == 'scheduled')
        {
            $posts = Post::scheduled()->with('category', 'author')->latest()->paginate($this->limit);
        }
        elseif($status == 'draft')
        {
            $posts = Post::draft()->with('category', 'author')->latest()->paginate($this->limit);
        }
        elseif($status == 'own')
        {
            $posts = $request->user()->posts()->with('category', 'author')->latest()->paginate($this->limit);
        }
        else
        {
            $posts = Post::withTrashed()->with('category', 'author')->latest()->paginate($this->limit);
        }
        return view('backend.blog.index', compact('posts', 'onlyTrashed'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(FormBuilder $formBuilder)
    {
        $form = $formBuilder->create(PostForm::class, [
            'method' => 'POST',
            'url' => route('backend.blog.store')
        ]);
        return view('backend.blog.edit', compact('form'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $form = $this->form(PostForm::class);

        // It will automatically use current request, get the rules, and do the validation
        if (!$form->isValid()) {
            return redirect()->back()->withErrors($form->getErrors())->withInput();
        }

        // Or automatically redirect on error. This will throw an HttpResponseException with redirect
        $form->redirectIfNotValid();

        $data = $form->getFieldValues();

        $post = $request->user()->posts()->create($data);
        $post->attachTags($data['post_tags']);

        return redirect()->route('backend.blog.index')->with('success', 'Your post was created successfully!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     *
     * @todo the controller does not receive Post object
     */
    public function edit($id, FormBuilder $formBuilder)
    {
        $post = Post::findOrFail($id);

        $form = $formBuilder->create(PostForm::class, [
            'method' => 'PUT',
            'url' => route('backend.blog.update', ['id' => $id]),
            'model' => $post
        ]);
        return view('backend.blog.edit', compact('form'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $form = $this->form(PostForm::class);

        // It will automatically use current request, get the rules, and do the validation
        if (!$form->isValid()) {
            return redirect()->back()->withErrors($form->getErrors())->withInput();
        }

        // Or automatically redirect on error. This will throw an HttpResponseException with redirect
        $form->redirectIfNotValid();

        $data = $form->getFieldValues();

        $post = Post::findOrFail($id);
        $post->update($data);
        $post->attachTags($data['post_tags']);

        return redirect()->route('backend.blog.index')->with('success', 'Your post was updated successfully!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Post::destroy($id);
        return redirect()->back()->with('trash-message', ['Your post was moved to trash!', $id]);
    }

    /**
     * @param $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function forceDestroy($id)
    {
        Post::onlyTrashed()->findOrFail($id)->forceDelete();
        return redirect()->back()->with('message', 'Your post was deleted permanently!');
    }

    /**
     * @param $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function restore($id)
    {
        Post::onlyTrashed()->findOrFail($id)->restore();
        return redirect()->back()->with('message', 'Your post was restored!');
    }
}

app/Http/Controllers/Backend/CategoryController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Category;
use App\Forms\CategoryForm;
use App\Http\Requests\CategoryDestroyRequest;
use App\Post;
use Illuminate\Http\Request;
use Kris\LaravelFormBuilder\FormBuilder;
use Kris\LaravelFormBuilder\FormBuilderTrait;

class CategoryController extends BackendController
{
    use FormBuilderTrait;

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::with('posts')->orderBy('title', 'asc')->paginate($this->limit);
        return view('backend.category.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(FormBuilder $formBuilder)
    {
        $form = $formBuilder->create(CategoryForm::class, [
            'method' => 'POST',
            'url' => route('backend.category.store')
        ]);
        return view('backend.category.edit', compact('form'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $form = $this->form(CategoryForm::class);

        // It will automatically use current request, get the rules, and do the validation
        if (!$form->isValid()) {
            return redirect()->back()->withErrors($form->getErrors())->withInput();
        }

        // Or automatically redirect on error. This will throw an HttpResponseException with redirect
        $form->redirectIfNotValid();

        Category::create($form->getFieldValues());
        return redirect()->route('backend.category.index')->with('success', 'Category was created successfully!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id, FormBuilder $formBuilder)
    {
        $category = Category::findOrFail($id);

        $form = $formBuilder->create(CategoryForm::class, [
            'method' => 'PUT',
            'url' => route('backend.category.update', ['id' => $id]),
            'model' => $category
        ]);
        return view('backend.category.edit', compact('form'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $form = $this->form(CategoryForm::class);

        // It will automatically use current request, get the rules, and do the validation
        if (!$form->isValid()) {
            return redirect()->back()->withErrors($form->getErrors())->withInput();
        }

        // Or automatically redirect on error. This will throw an HttpResponseException with redirect
        $form->redirectIfNotValid();

        $category = Category::findOrFail($id);
        $category->update($form->getFieldValues());

        return redirect()->route('backend.category.index')->with('success', 'Your category was updated successfully!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(CategoryDestroyRequest $request, $id)
    {
        Post::withTrashed()->where('category_id', $id)->update(['category_id' => config('cms.default_category_id')]);
        Category::destroy($id);
        return redirect()->back()->with('message', 'Your category was deleted!');
    }
}

app/Http/Controllers/Backend/HomeController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Forms\AccountForm;
use Illuminate\Http\Request;
use Kris\LaravelFormBuilder\FormBuilder;
use Kris\LaravelFormBuilder\FormBuilderTrait;

class HomeController extends BackendController
{
    use FormBuilderTrait;

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('backend.home');
    }

    public function edit(Request $request, FormBuilder $formBuilder)
    {
        $user = $request->user();

        $form = $formBuilder->create(AccountForm::class, [
            'method' => 'PUT',
            'url' => route('backend.account.update'),
            'model' => $user
        ]);
        return view('backend.user.edit', compact('form'));
    }

    public function update(Request $request)
    {
        $form = $this->form(AccountForm::class);

        // It will automatically use current request, get the rules, and do the validation
        if (!$form->isValid()) {
            return redirect()->back()->withErrors($form->getErrors())->withInput();
        }

        // Or automatically redirect on error. This will throw an HttpResponseException with redirect
        $form->redirectIfNotValid();

        $user = $request->user();
        $user->update($form->getFieldValues());

        return redirect()->route('home')->with('success', 'Your account was updated successfully!');
    }
}

app/Http/Controllers/Backend/TagController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Forms\TagForm;
use App\Tag;
use Illuminate\Http\Request;
use Kris\LaravelFormBuilder\FormBuilder;
use Kris\LaravelFormBuilder\FormBuilderTrait;

class TagController extends BackendController
{
    use FormBuilderTrait;

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $tags = Tag::with('posts')->orderBy('name', 'asc')->paginate($this->limit);
        return view('backend.tag.index', compact('tags'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(FormBuilder $formBuilder)
    {
        $form = $formBuilder->create(TagForm::class, [
            'method' => 'POST',
            'url' => route('backend.tag.store')
        ]);
        return view('backend.tag.edit', compact('form'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $form = $this->form(TagForm::class);

        // It will automatically use current request, get the rules, and do the validation
        if (!$form->isValid()) {
            return redirect()->back()->withErrors($form->getErrors())->withInput();
        }

        // Or automatically redirect on error. This will throw an HttpResponseException with redirect
        $form->redirectIfNotValid();

        Tag::create($form->getFieldValues());
        return redirect()->route('backend.tag.index')->with('success', 'Tag was created successfully!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id, FormBuilder $formBuilder)
    {
        $tag = Tag::findOrFail($id);

        $form = $formBuilder->create(TagForm::class, [
            'method' => 'PUT',
            'url' => route('backend.tag.update', ['id' => $id]),
            'model' => $tag
        ]);
        return view('backend.tag.edit', compact('form'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $form = $this->form(TagForm::class);

        // It will automatically use current request, get the rules, and do the validation
        if (!$form->isValid()) {
            return redirect()->back()->withErrors($form->getErrors())->withInput();
        }

        // Or automatically redirect on error. This will throw an HttpResponseException with redirect
        $form->redirectIfNotValid();

        $tag = Tag::findOrFail($id);
        $tag->update($form->getFieldValues());

        return redirect()->route('backend.tag.index')->with('success', 'Your tag was updated successfully!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Tag::destroy($id);
        return redirect()->back()->with('message', 'Your tag was deleted!');
    }
}

resources/views/backend/user/confirm.blade.php
@extends('layouts.backend.main')

@section('title', 'MyBlog | Delete Confirmation')))

@section('content')
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                User
                <small>Delete Confirmation</small>
            </h1>
            <ol class="breadcrumb">
                <li><i class="fa fa-dashboard"></i> <a href="{{ route('home') }}">Dashboard</a></li>
                <li><a href="{{ route('backend.user.index') }}">Users</a></li>
                <li class="active">Delete Confirmation</li>
            </ol>
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-xs-12">
                    <div class="box">
                        {!! Form::open(['method' => 'DELETE', 'route' => ['backend.user.destroy', $user->id]]) !!}
                        <div class="box-body">
                            <p>You have specified this user for deletion:</p>
                            <p>ID #{{ $user->id }}: {{ $user->name }}</p>
                            <p>What should be done with content owned by this user?</p>
                            <p>{!! Form::input('radio', 'delete_option', 'delete', ['checked' => 'checked']) !!} Delete All Content</p>
                            <p>
                                {!! Form::input('radio', 'delete_option', 'attribute') !!} Attribute content to:
                                {!! Form::select('selected_user', \App\User::where('id', '!=', $user->id)->pluck('name', 'id'), null) !!}
                            </p>
                        </div>
                        <div class="box-footer">
                            {!! Form::button('Confirm Deletion', ['type' => 'submit', 'class' => 'btn btn-danger']) !!}
                            <a href="{{ route('backend.user.index') }}" class="btn btn-default">Cancel</a>
                        </div>
                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
            <!-- ./row -->
        </section>
        <!-- /.content -->
    </div>
@endsection

resources/views/backend/user/edit.blade.php
@extends('layouts.backend.main')

@section('title', 'MyBlog | ' . (($form->getModel() ? 'Edit user' : 'Add new user')))

@section('content')
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                User
                <small>@if($form->getModel()) Edit user @else Add new user @endif</small>
            </h1>
            <ol class="breadcrumb">
                <li><i class="fa fa-dashboard"></i> <a href="{{ route('home') }}">Dashboard</a></li>
                <li><a href="{{ route('backend.user.index') }}">Users</a></li>
                @if($form->getModel())
                <li class="active">Edit</li>
                @else
                <li class="active">Add new</li>
                @endif
            </ol>
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-xs-12">
                    <div class="box">
                        <div class="box-body">
                            {!! form($form) !!}
                        </div>
                    </div>
                </div>
            </div>
            <!-- ./row -->
        </section>
        <!-- /.content -->
    </div>
@endsection

@section('script')
<script>
    $('#name').on('blur', function(){
        var theTitle = this.value.toLowerCase().trim(),
            slugInput = $('#slug'),
            theSlug = theTitle.replace(/&/g, '-and-')
                                .replace(/[^a-z0-9-]+/g, '-')
                                .replace(/\-\-+/g, '')
                                .replace(/^-+|-+$/g, '');

        slugInput.val(theSlug);
    });
    var bioEditor = new SimpleMDE({ element: $("#bio")[0] });
</script>
@endsection

resources/views/backend/user/index.blade.php
@extends('layouts.backend.main')

@section('title', 'MyBlog | Users')

@section('content')
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                User
                <small>Display all users</small>
            </h1>
            <ol class="breadcrumb">
                <li><i class="fa fa-dashboard"></i> <a href="{{ route('home') }}">Dashboard</a></li>
                <li><a href="{{ route('backend.user.index') }}">Users</a></li>
                <li class="active">All Users</li>
            </ol>
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-xs-12">
                    <div class="box">
                        <div class="box-header clearfix">
                            <div class="pull-left">
                                <a href="{{ route('backend.user.create') }}" class="btn btn-success"><i class="fa fa-plus"></i> Add New</a>
                            </div>
                        </div>
                        <!-- /.box-header -->
                        <div class="box-body ">
                            @include('backend.partials.message')
                            <table class="table table-bordered">
                                <thead>
                                    <tr>
                                        <td width="70">Action</td>
                                        <td>Name</td>
                                        <td>Email</td>
                                        <td>Role</td>
                                        <td>Posts Count</td>
                                    </tr>
                                </thead>
                                <tbody>
                                @forelse($users as $user)
                                    <tr>
                                        <td>
                                            <a href="{{ route('backend.user.edit', $user->id) }}" class="btn btn-xs btn-default">
                                                <i class="fa fa-edit"></i>
                                            </a>
                                            @if($user->id == config('cms.default_user_id') || $user->id == auth()->user()->id)
                                                <button onclick="return false;" type="submit" class="btn btn-xs btn-danger disabled">
                                                    <i class="fa fa-times"></i>
                                                </button>
                                            @else
                                                <a href="{{ route('backend.user.confirm', [$user->id]) }}" type="submit" class="btn btn-xs btn-danger">
                                                    <i class="fa fa-times"></i>
                                                </a>
                                            @endif
                                        </td>
                                        <td>{{ $user->name }}</td>
                                        <td>{{ $user->email }}</td>
                                        <td>{{ $user->roles->first()->display_name }}</td>
                                        <td>{{ $user->posts()->withTrashed()->count() }}</td>
                                    </tr>
                                @empty
                                    <tr>
                                        <td colspan="2">
                                            <div class="alert alert-danger">
                                                <strong>No record found</strong>
                                            </div>
                                        </td>
                                    </tr>
                                @endforelse
                                </tbody>
                            </table>
                        </div>
                        <!-- /.box-body -->
                        <div class="box-footer clearfix">
                            <div class="pull-left">
                                {{ $users->render() }}
                            </div>
                            <div class="pull-right">
                                <small>
                                    <?php $usersCount = $users->total() ?>
                                    {{ $usersCount }} {{ \Illuminate\Support\Str::plural('user', $usersCount) }}
                                </small>
                            </div>
                        </div>
                    </div>
                    <!-- /.box -->
                </div>
            </div>
            <!-- ./row -->
        </section>
        <!-- /.content -->
    </div>
@endsection

@section('script')
<script>
    $('ul.pagination').addClass('no-margin pagination-sm');
</script>
@endsection